<h2>Manage Article</h2>

<!-- .row -->
<div class="row">
    <div class="col-md-12">
        <table id="articleTable" class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Author</th>
                    <th>
                        Action
                            <button onclick="add()" style="margin-left: 4px;" type="button" class="btn btn-success btn-circle btn-sm btn-circle"><i class="fa fa-plus"></i></button>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<!-- .row -->

<div class="modal fade" id="articleModal" role="dialog" aria-labelledby="exampleModalLabel1"
style="z-index: 1041 !important;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel1">Network</h4> </div>
            <div class="modal-body">
                <form id="articleForm" data-toggle="validator" data-delay="100">
                    <input type="hidden" name="id">
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Title</label>
                        <input type="text" class="form-control" name="title">
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Content</label>
                        <textarea name="content" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Author</label>
                        <input type="text" class="form-control" name="author" value="adepanges">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button id="btnSaveArticle" type="button" class="btn btn-primary">Simpan</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.app = {
        site_url: '<?php echo $url->getStaticBaseUri() ?>'
    }
</script>
